### ISSUE TITLE
Enhancement requests

### ISSUE THREAD

**Issue by mikequinlan** [tallesl/net-L#3]
I see a few enhancement/change requests on the Reddit threads. Are there any that you want to implement that I could help with? Here are the ones I've seen so far.

- Use atomic appends https://www.reddit.com/r/dotnet/comments/5zt3cn/l_a_configless_logger_xpost_rcsharp/df1lhk6
- Add LogAsync method https://www.reddit.com/r/csharp/comments/5zt31e/l_a_zero_configuration_logging_library/df0vhh6/
- Ignore case of format name https://www.reddit.com/r/csharp/comments/5zt31e/l_a_zero_configuration_logging_library/df0vhh6/
- Remove static constructor https://www.reddit.com/r/csharp/comments/5zt31e/l_a_zero_configuration_logging_library/df0vhh6/

**Comment by tallesl** [comment]
I'm definitely doing those. I'll probably implement just as I commented [here](https://www.reddit.com/r/csharp/comments/5zt31e/l_a_zero_configuration_logging_library/df18rag/) (plus the atomic append suggested on /r/dotnet).

They seen to be fairly simply to implement to be honest, but I'll gladly accept some help on testing it.

Thanks for passing by!
