### ISSUE TITLE
Library\OpenStreams.cs:行号 54

### ISSUE THREAD

**Issue by 48355746** [tallesl/net-L#4]
System.InvalidOperationException: 集合已修改；可能无法执行枚举操作。
   在 System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   在 System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
   在 System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   在 LLibrary.OpenStreams.ClosePastStreams(Object ignored) 位置 A:\GitHub\net-L\Library\OpenStreams.cs:行号 54
   在 System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.TimerQueueTimer.CallCallback()
   在 System.Threading.TimerQueueTimer.Fire()
   在 System.Threading.TimerQueue.FireNextTimers()
   在 System.Threading.TimerQueue.AppDomainTimerCallback()

**Comment by tallesl** [comment]
see #5
