### ISSUE TITLE
Strong named version

### ISSUE THREAD

**Issue by thecolour** [tallesl/net-L#6]
Hi, thanks for sharing. 

Would you consider creating a signed version of the package assembly? This would mean that the assembly could be called by both signed and unsigned code. As it is it cannot be called by signed code. If not, would you be happy for me to fork it?

**Comment by tallesl** [comment]
Hi, I'm not used to dealing with signing assemblies, so I'm afraid I'm won't be doing it.
Feel free to fork it, just make sure to match the versions (git tag) to avoid confusion.
